### ISSUE TITLE
Can update the rubygems version?

### ISSUE THREAD

**Issue by TangMonk** [DavyJonesLocker/client_side_validations#614] opened 2015-05-13 07:09 UTC
and simple_form plugin.

thanks

**Comment by tagliala** [comment] 2015-05-13 07:52
Sorry, still can't :)

Duplicate of #610, closing here

**Closed by tagliala** 2015-05-13 07:52 UTC

**Comment by tagliala** [comment] 2015-05-13 07:53
Also, simple form plugin needs a fix #38 and I must fix this before releasing

**Comment by TangMonk** [comment] 2015-05-13 12:55
thanks, :D
