### ISSUE TITLE
Conditional validation doesn't work on multiple conditions

### ISSUE THREAD

**Issue by zll11111** [DavyJonesLocker/client_side_validations#756] opened 2019-04-07 09:56 UTC
model file:
` validates :realname, presence: true,,if: [:is_a?, :is_b?, :is_c?]`

view file:
`   <%= f.input :realname,  :input_html => { :validate => true }, required: true   %>`
 or`    <%= f.input :realname,   :validate => true , required: true   %>`
the realname field is not validated on the client side.

Only if I combile :is_a?, :is_b?, :is_c? into :is_above_a?, and the model is like this:
` validates :realname, presence: true,,if: :is_above_a?`
then it works.

So I suppose something is wrong when multiple conditions is used.

**Comment by tagliala** [comment] 2019-04-07 15:54
Hi,

I'm unable to replicate this

Rails 5.2.3
Ruby 2.6.0
CSV 13.1.0
CSV-simple_form 6.9.0

Model
```rb
# frozen_string_literal: true

class Post < ApplicationRecord
  # validates :title, uniqueness: true
  validates :title, presence: true, if: [:hello?, :world?]

  def hello?
    true
  end

  def world?
    true
  end
end
```

Form:
```erb
<%= simple_form_for(@post, validate: true) do |f| %>
  <%= f.input :title, validate: true %>
  <div class="field">
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  </div>
<% end %>
```

Output:
![image](https://user-images.githubusercontent.com/556268/55686155-f5ab8500-595d-11e9-8185-ac54ce543530.png)

**Comment by zll11111** [comment] 2019-05-24 13:19
My gem versions are :
ruby 2.5.1
rails (5.2.2)
client_side_validations (11.1.3)
client_side_validations-simple_form (6.8.0)

**Comment by tagliala** [comment] 2019-05-24 14:14
@zll11111

Please upgrade to the latest versions and use `<%= f.input :title, validate: true %>`, because I'm not able to reproduce

Please provide a reproducible reduced test case and share the repository somewhere

Meanwhile, closing here

**Closed by tagliala** 2019-05-24 14:14 UTC
Labels: need feedback
