### ISSUE TITLE
ActionView::Template::Error

### ISSUE THREAD

**Issue by ahmadhasankhan** [DavyJonesLocker/client_side_validations#632] opened 2015-08-17 10:46 UTC
Hey is this compatible with Rails4?

I am getting this exception.
```
ActionView::Template::Error (wrong number of arguments (3 for 2)):
    1: <%= form_for(@user,  validate: true) do |f| %>
    2:     <% if @user.errors.any? %>
    3:         <div id="error_explanation">
    4:             <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
  app/views/users/_form.html.erb:1:in `_app_views_users__form_html_erb__2332053212526807052_70182875868800'
  app/views/users/new.html.erb:6:in `_app_views_users_new_html_erb___4074872932544590043_70182862873760'
```

**Comment by tagliala** [comment] 2015-08-17 14:20
Master branch works

Duplicate of #603

**Closed by tagliala** 2015-08-17 14:20 UTC

**Comment by ahmadhasankhan** [comment] 2015-08-17 14:52
Tried 4-2-stable blanch and works fine.
