### ISSUE TITLE
Possible conflict jQuery rails-ujs that impedes validations

### ISSUE THREAD

**Issue by dvodvo** [DavyJonesLocker/client_side_validations#763] opened 2019-08-08 08:00 UTC
Gemfile lock has the following block

```
    client_side_validations (15.0.0)
      jquery-rails (~> 4.3)
      js_regex (~> 3.1)
      rails (>= 5.0.0.1, < 6.1)
```
The application.js file by default comes with `//= require rails-ujs`
which for AJAX calls can conflict with jQuery.  So this application now has
```
Using jquery-rails 4.3.5
Using jquery-ui-rails 6.0.1
Using rails-jquery-autocomplete 1.0.5
```
the initializer loads properly (`<script src="/assets/rails.validations.self-90b85c56524b44f917184c411de656d3ab2f65088b7dfc0223f79e1e909cfb4a.js?body=1" data-turbolinks-track="reload"></script>`) and has the following block uncommented 
```
 ActionView::Base.field_error_proc = proc do |html_tag, instance|
   if html_tag =~ /^<label/
     %(<div class="field_with_errors">#{html_tag}</div>).html_safe
   else
     %(<div class="field_with_errors">#{html_tag}<label for="#{instance.send(:tag_id)}" class="message">#{instance.error_message.first}</label></div>).html_safe
   end
 end
```
The form has the tag `<%= form_with(model: link, local: true, validate: true) do |form| %>`  which renders correctly based on attributes name and link needing to be present

```
<form action="/links?locale=en" accept-charset="UTF-8" novalidate="novalidate" data-client-side-validations="{&quot;html_settings&quot;:{&quot;type&quot;:&quot;ActionView::Helpers::FormBuilder&quot;,&quot;input_tag&quot;:&quot;\u003cdiv class=\&quot;field_with_errors\&quot;\u003e\u003cspan id=\&quot;input_tag\&quot; /\u003e\u003clabel for=\&quot;\&quot; class=\&quot;message\&quot;\u003e\u003c/label\u003e\u003c/div\u003e&quot;,&quot;label_tag&quot;:&quot;\u003cdiv class=\&quot;field_with_errors\&quot;\u003e\u003clabel id=\&quot;label_tag\&quot; /\u003e\u003c/div\u003e&quot;},&quot;number_format&quot;:{&quot;separator&quot;:&quot;.&quot;,&quot;delimiter&quot;:&quot;,&quot;},&quot;validators&quot;:{&quot;link[name]&quot;:{&quot;presence&quot;:[{&quot;message&quot;:&quot;can&#39;t be blank&quot;}]},&quot;link[link]&quot;:{&quot;presence&quot;:[{&quot;message&quot;:&quot;can&#39;t be blank&quot;}]}}}" method="post">
 
<input type="text" name="link[name]" id="link_name" /> 
<textarea name="link[link]" id="link_link">
```
However the form does not fire error messages when tabbing through the aformentioned fields (there are two forms with clients side validations on the page).  Can this be a result of conflict jQuery / rails-ujs? [I was also used to seeing a javascript block in rails4 versions using CSV gem and it does not appear here, but that may be due to v5 changes]

**Comment by tagliala** [comment] 2019-08-08 08:52
Hi,

thanks for being parte of the CSV community.

Debugging CSV issues is a really time consuming task.

CSV depends on jquery rails and should not have conflict with rails-ujs because I'm using them both.

I cannot replicate this issue. The validation of the provided snippet is working for me.

- ruby 2.6.3
- rails 5.2.3
- csv 15.0

### initializer
```rb
ActionView::Base.field_error_proc = proc do |html_tag, instance|
  if html_tag =~ /^<label/
    %(<div class="field_with_errors">#{html_tag}</div>).html_safe
  else
    %(<div class="field_with_errors">#{html_tag}<label for="#{instance.send(:tag_id)}" class="message">#{instance.error_message.first}</label></div>).html_safe
  end
end
```

### form
```
```

Please note that if your application using autocompletion on fields you may need extra steps: https://github.com/DavyJonesLocker/client_side_validations/wiki/jQuery-Plugins

> [I was also used to seeing a javascript block in rails4 versions using CSV gem and it does not appear here, but that may be due to v5 changes]

Yes, CSV 9.0 switched to unobtrusive javascript so you can avoid inline css and it is CORS friendly: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CHANGELOG.md#900--2017-01-31

**Comment by tagliala** [comment] 2019-08-08 09:02
Closing here, I will reopen if you can provide a reproducible test case

**Closed by tagliala** 2019-08-08 09:02 UTC

**Comment by tagliala** [comment] 2019-08-11 10:32
Side note: require `rails-ujs` after `jquery`, otherwise you will not be able to use `$.rails`
